name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Full Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          user: MatheusAgueda
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          config_timezone: Europe/Lisbon
          config_output: svg
          output_action: commit
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_sections: most-used
          plugin_languages_details: percentage, bytes-size
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 30
          plugin_habits_from: 200
          plugin_habits_trim: yes

      - name: Languages Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics-languages.svg
          user: MatheusAgueda
          template: classic
          base: ""
          config_output: svg
          output_action: commit
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 12
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: percentage, bytes-size, lines

      - name: Habits Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics-habits.svg
          user: MatheusAgueda
          template: classic
          base: ""
          config_output: svg
          output_action: commit
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_trim: yes
